package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.pokepet.model.ActActivityRegister;

public interface ActActivityRegisterMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity_register
	 * @mbggenerated  Mon Nov 05 14:35:21 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String registerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity_register
	 * @mbggenerated  Mon Nov 05 14:35:21 GMT+08:00 2018
	 */
	int insert(ActActivityRegister record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity_register
	 * @mbggenerated  Mon Nov 05 14:35:21 GMT+08:00 2018
	 */
	int insertSelective(ActActivityRegister record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity_register
	 * @mbggenerated  Mon Nov 05 14:35:21 GMT+08:00 2018
	 */
	ActActivityRegister selectByPrimaryKey(String registerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity_register
	 * @mbggenerated  Mon Nov 05 14:35:21 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(ActActivityRegister record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity_register
	 * @mbggenerated  Mon Nov 05 14:35:21 GMT+08:00 2018
	 */
	int updateByPrimaryKeyWithBLOBs(ActActivityRegister record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity_register
	 * @mbggenerated  Mon Nov 05 14:35:21 GMT+08:00 2018
	 */
	int updateByPrimaryKey(ActActivityRegister record);

	int selectMaxNoForActivity(String activityId);
    
    List<Map<String, Object>> getRegisterListByParam(Map<String, Object> param);
    
    Map<String, Object> getRegister(@Param("registerId") String registerId, @Param("userId") String userId);
    
    ActActivityRegister getRegisterByActivityIdAndUserId(@Param("activityId") String activityId, @Param("userId") String userId);
}