package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import com.pokepet.model.ActActivity;

public interface ActActivityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity
	 * @mbggenerated  Tue Nov 20 01:51:18 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity
	 * @mbggenerated  Tue Nov 20 01:51:18 GMT+08:00 2018
	 */
	int insert(ActActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity
	 * @mbggenerated  Tue Nov 20 01:51:18 GMT+08:00 2018
	 */
	int insertSelective(ActActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity
	 * @mbggenerated  Tue Nov 20 01:51:18 GMT+08:00 2018
	 */
	ActActivity selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity
	 * @mbggenerated  Tue Nov 20 01:51:18 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(ActActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table act_activity
	 * @mbggenerated  Tue Nov 20 01:51:18 GMT+08:00 2018
	 */
	int updateByPrimaryKey(ActActivity record);

	List<Map<String, Object>> getActivityList();

	Map<String,Object> getActivityStatistics(String id);
}