package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import com.pokepet.model.ActActivityRegister;

public interface ActActivityRegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_activity_register
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String registerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_activity_register
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    int insert(ActActivityRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_activity_register
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    int insertSelective(ActActivityRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_activity_register
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    ActActivityRegister selectByPrimaryKey(String registerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_activity_register
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(ActActivityRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_activity_register
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    int updateByPrimaryKeyWithBLOBs(ActActivityRegister record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table act_activity_register
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    int updateByPrimaryKey(ActActivityRegister record);
    
    int selectMaxNoForActivity(String activityId);
    
    List<Map<String, Object>> getRegisterListByParam(Map<String, Object> param);
}