package com.pokepet.dao;

import com.pokepet.model.CmsBanner;

import java.util.List;

public interface CmsBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    int deleteByPrimaryKey(String bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    int insert(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    int insertSelective(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    CmsBanner selectByPrimaryKey(String bannerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    int updateByPrimaryKeySelective(CmsBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_banner
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    int updateByPrimaryKey(CmsBanner record);


    List<CmsBanner> selectEffectiveBannerList();

}