package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.pokepet.model.Commodity;


public interface CommodityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 15:37:23 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String commodityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 15:37:23 GMT+08:00 2018
	 */
	int insert(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 15:37:23 GMT+08:00 2018
	 */
	int insertSelective(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 15:37:23 GMT+08:00 2018
	 */
	Commodity selectByPrimaryKey(String commodityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 15:37:23 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 15:37:23 GMT+08:00 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 15:37:23 GMT+08:00 2018
	 */
	int updateByPrimaryKey(Commodity record);

	public List<Map<String, Object>> selectCommodityList(Map<String, Object> param);
}