package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import com.pokepet.model.Commodity;


public interface CommodityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String commodityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	int insert(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	int insertSelective(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	Commodity selectByPrimaryKey(String commodityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	int updateByPrimaryKey(Commodity record);

	public List<Map<String, Object>> selectCommodityList(Map<String, Object> param);
	
	public List<Map<String, Object>> selectCommodityListForMall(Map<String, Object> param);
	
	public Map<String, Object> selectCommodityInfoForMall(String commodityId);
}