package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.Commodity;

public interface CommodityMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 13:42:31 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String commodityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 13:42:31 GMT+08:00 2018
	 */
	int insert(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 13:42:31 GMT+08:00 2018
	 */
	int insertSelective(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 13:42:31 GMT+08:00 2018
	 */
	Commodity selectByPrimaryKey(String commodityId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 13:42:31 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 13:42:31 GMT+08:00 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Commodity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table commodity
	 * @mbggenerated  Tue Sep 18 13:42:31 GMT+08:00 2018
	 */
	int updateByPrimaryKey(Commodity record);

	public List<Commodity> getCommodityList(String search, List<String> typeList, List<String> brandList,
			int iDisplayStart, int iDisplayLength);
}