package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.ExplorePoint;

public interface ExplorePointMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table explore_point
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String pointId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table explore_point
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	int insert(ExplorePoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table explore_point
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	int insertSelective(ExplorePoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table explore_point
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	ExplorePoint selectByPrimaryKey(String pointId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table explore_point
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(ExplorePoint record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table explore_point
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	int updateByPrimaryKey(ExplorePoint record);
	
	List<ExplorePoint> getPointListWithPointStar(int pointStar);
}