package com.pokepet.dao;

import com.pokepet.model.MessageQueue;

import java.util.List;
import java.util.Map;

public interface MessageQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_queue
     *
     * @mbggenerated Sun Oct 07 01:36:18 CST 2018
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_queue
     *
     * @mbggenerated Sun Oct 07 01:36:18 CST 2018
     */
    int insert(MessageQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_queue
     *
     * @mbggenerated Sun Oct 07 01:36:18 CST 2018
     */
    int insertSelective(MessageQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_queue
     *
     * @mbggenerated Sun Oct 07 01:36:18 CST 2018
     */
    MessageQueue selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_queue
     *
     * @mbggenerated Sun Oct 07 01:36:18 CST 2018
     */
    int updateByPrimaryKeySelective(MessageQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_queue
     *
     * @mbggenerated Sun Oct 07 01:36:18 CST 2018
     */
    int updateByPrimaryKey(MessageQueue record);


    List<Map<String,String>> getMessageList(String userId);

    Map<String,String> getMessageNeedFollowPetInfo(String petId);

    Map<String,String> getMessageNeedFollowUserInfo(String followUserId);

    int selectMessageCount(MessageQueue messageQueue);
}