package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import com.pokepet.model.OrderPay;

public interface OrderPayMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_pay
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_pay
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	int insert(OrderPay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_pay
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	int insertSelective(OrderPay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_pay
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	OrderPay selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_pay
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(OrderPay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_pay
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	int updateByPrimaryKey(OrderPay record);

	List<Map<String, Object>> selectCommodityList(Map<String, Object> param);
	
	/**
	 * 
	 * @param userId
	 * @return
	 */
	OrderPay selectLastUnfilledOrderByUserId(String userId);
	
	/**
	 * 
	 * @param userId
	 * @param commodityId
	 * @param dayRange
	 * @return
	 */
	OrderPay selectLastCommodityOrderByUserId(String userId,String commodityId,int dayRange);
}