package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.pokepet.model.OrderMall;

public interface OrderMallMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table order_mall
	 *
	 * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table order_mall
	 *
	 * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
	 */
	int insert(OrderMall record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table order_mall
	 *
	 * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
	 */
	int insertSelective(OrderMall record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table order_mall
	 *
	 * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
	 */
	OrderMall selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table order_mall
	 *
	 * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(OrderMall record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table order_mall
	 *
	 * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
	 */
	int updateByPrimaryKey(OrderMall record);

	List<Map<String, Object>> selectCommodityList(Map<String, Object> param);

	/**
	 *
	 * @param userId
	 * @return
	 */
	OrderMall selectLastUnfilledOrderByUserId(String userId);

	/**
	 *
	 * @param userId
	 * @param commodityId
	 * @param dayRange
	 * @return
	 */
	OrderMall selectLastCommodityOrderByUserId(@Param("userId") String userId,@Param("commodityId") String commodityId,@Param("dayRange") int dayRange);

	List<OrderMall> selectOrderListByUserId(@Param("userId") String userId);

	List<Map<String,String>> selectOrderList(@Param("userId") String userId);

	Map<String,String> getOrderDetail(String orderId);
}