package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import com.pokepet.model.OrderPay;

public interface OrderPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Wed Aug 22 10:06:12 CST 2018
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Wed Aug 22 10:06:12 CST 2018
     */
    int insert(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Wed Aug 22 10:06:12 CST 2018
     */
    int insertSelective(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Wed Aug 22 10:06:12 CST 2018
     */
    OrderPay selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Wed Aug 22 10:06:12 CST 2018
     */
    int updateByPrimaryKeySelective(OrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_pay
     *
     * @mbggenerated Wed Aug 22 10:06:12 CST 2018
     */
    int updateByPrimaryKey(OrderPay record);

	List<Map<String, Object>> selectCommodityList(Map<String, Object> param);
}