package com.pokepet.dao;

import com.pokepet.model.PetAlbum;

import java.util.List;

public interface PetAlbumMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Fri May 25 15:31:10 CST 2018
	 */
	int deleteByPrimaryKey(String petId);



	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Fri May 25 15:31:10 CST 2018
	 */
	int insertSelective(PetAlbum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Fri May 25 15:31:10 CST 2018
	 */
	List<PetAlbum> selectAlbumByPrimaryKey(String petId);

	List<PetAlbum> selectAlbumByPetId(String petId);


}