package com.pokepet.dao;

import com.pokepet.model.PetFollow;

import java.util.Map;

public interface PetFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Mon Sep 24 13:31:57 CST 2018
     */
    int deleteByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Mon Sep 24 13:31:57 CST 2018
     */
    int insert(PetFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Mon Sep 24 13:31:57 CST 2018
     */
    int insertSelective(PetFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Mon Sep 24 13:31:57 CST 2018
     */
    PetFollow selectByPrimaryKey(String followId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Mon Sep 24 13:31:57 CST 2018
     */
    int updateByPrimaryKeySelective(PetFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_follow
     *
     * @mbggenerated Mon Sep 24 13:31:57 CST 2018
     */
    int updateByPrimaryKey(PetFollow record);

    PetFollow selectByUserIdAndPetId(Map<String,String> map);
}