package com.pokepet.dao;

import org.apache.ibatis.annotations.Param;

import com.pokepet.model.PetLike;

public interface PetLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Tue Jun 05 16:41:53 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Tue Jun 05 16:41:53 CST 2018
     */
    int insert(PetLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Tue Jun 05 16:41:53 CST 2018
     */
    int insertSelective(PetLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Tue Jun 05 16:41:53 CST 2018
     */
    PetLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Tue Jun 05 16:41:53 CST 2018
     */
    int updateByPrimaryKeySelective(PetLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_like
     *
     * @mbggenerated Tue Jun 05 16:41:53 CST 2018
     */
    int updateByPrimaryKey(PetLike record);
    
    int delPetLike(@Param("petId") String petId,@Param("userId") String userId);
	
	int getLikeCountByPetId(String petId);
}