package com.pokepet.dao;

import com.pokepet.model.Pet;

public interface PetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Thu May 24 14:33:57 CST 2018
	 */
	int deleteByPrimaryKey(String petId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Thu May 24 14:33:57 CST 2018
	 */
	int insert(Pet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Thu May 24 14:33:57 CST 2018
	 */
	int insertSelective(Pet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Thu May 24 14:33:57 CST 2018
	 */
	Pet selectByPrimaryKey(String petId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Thu May 24 14:33:57 CST 2018
	 */
	int updateByPrimaryKeySelective(Pet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Thu May 24 14:33:57 CST 2018
	 */
	int updateByPrimaryKey(Pet record);
}