package com.pokepet.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.pokepet.model.Pet;

public interface PetMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Sat Jul 07 11:37:56 GMT+08:00 2018
	 */
	int insert(Pet record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet
	 * @mbggenerated  Sat Jul 07 11:37:56 GMT+08:00 2018
	 */
	int insertSelective(Pet record);

	List<Pet> getPetListByUserId(String userId);

	String getMaxPetNo(@Param("petIdStart") String petIdStart,@Param("year") String year);
	
}