package com.pokepet.dao;

import com.pokepet.model.PetRecord;

import java.util.List;

public interface PetRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_record
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_record
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    int insert(PetRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_record
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    int insertSelective(PetRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_record
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    PetRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_record
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    int updateByPrimaryKeySelective(PetRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_record
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PetRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pet_record
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    int updateByPrimaryKey(PetRecord record);


    List<PetRecord> getUserRecordsByUserId(String userId);

}