package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.PetSupply;

public interface PetSupplyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String supplyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	int insert(PetSupply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	int insertSelective(PetSupply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	PetSupply selectByPrimaryKey(String supplyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(PetSupply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	int updateByPrimaryKey(PetSupply record);

	List<PetSupply> getSupplyListWithPointStar(int pointStar);
	
	List<PetSupply> getSupplyList();
}