package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.PetSupply;

public interface PetSupplyMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Tue Aug 07 16:45:12 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String supplyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Tue Aug 07 16:45:12 GMT+08:00 2018
	 */
	int insert(PetSupply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Tue Aug 07 16:45:12 GMT+08:00 2018
	 */
	int insertSelective(PetSupply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Tue Aug 07 16:45:12 GMT+08:00 2018
	 */
	PetSupply selectByPrimaryKey(String supplyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Tue Aug 07 16:45:12 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(PetSupply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_supply
	 * @mbggenerated  Tue Aug 07 16:45:12 GMT+08:00 2018
	 */
	int updateByPrimaryKey(PetSupply record);

	/**
	 * 根据探索点星级获取补给列�?
	 * @param pointStar
	 * @return
	 */
	List<PetSupply> getSupplyListWithPointStar(int pointStar);
}