package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.PetWeapon;

public interface PetWeaponMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String weaponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	int insert(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	int insertSelective(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	PetWeapon selectByPrimaryKey(String weaponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	int updateByPrimaryKey(PetWeapon record);

	List<PetWeapon> getWeaponListWithPointStar(int pointStar);
	
	List<PetWeapon> getWeaponList();
}