package com.pokepet.dao;

import com.pokepet.model.PetWeapon;

public interface PetWeaponMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String weaponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	int insert(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	int insertSelective(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	PetWeapon selectByPrimaryKey(String weaponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	int updateByPrimaryKey(PetWeapon record);
}