package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.PetWeapon;

public interface PetWeaponMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Tue Aug 07 15:46:21 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String weaponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Tue Aug 07 15:46:21 GMT+08:00 2018
	 */
	int insert(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Tue Aug 07 15:46:21 GMT+08:00 2018
	 */
	int insertSelective(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Tue Aug 07 15:46:21 GMT+08:00 2018
	 */
	PetWeapon selectByPrimaryKey(String weaponId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Tue Aug 07 15:46:21 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(PetWeapon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pet_weapon
	 * @mbggenerated  Tue Aug 07 15:46:21 GMT+08:00 2018
	 */
	int updateByPrimaryKey(PetWeapon record);

	/**
	 * 根据探索点星级获取装备列表
	 * @param pointStar
	 * @return
	 */
	List<PetWeapon> getWeaponListWithPointStar(int pointStar);
}