package com.pokepet.dao;

import com.pokepet.model.RecordVisit;

public interface RecordVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    int insert(RecordVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    int insertSelective(RecordVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    RecordVisit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    int updateByPrimaryKeySelective(RecordVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_visit
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    int updateByPrimaryKey(RecordVisit record);
}