package com.pokepet.dao;

import com.pokepet.model.RecordCollect;
import org.apache.ibatis.annotations.Param;

public interface RecordCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Mon Sep 24 01:26:59 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Mon Sep 24 01:26:59 CST 2018
     */
    int insert(RecordCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Mon Sep 24 01:26:59 CST 2018
     */
    int insertSelective(RecordCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Mon Sep 24 01:26:59 CST 2018
     */
    RecordCollect selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Mon Sep 24 01:26:59 CST 2018
     */
    int updateByPrimaryKeySelective(RecordCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_collect
     *
     * @mbggenerated Mon Sep 24 01:26:59 CST 2018
     */
    int updateByPrimaryKey(RecordCollect record);

    RecordCollect selectByUserIdAndRecordId(@Param("userId")String userId,@Param("recordId")String recordId);
}