package com.pokepet.dao;

import com.pokepet.model.ShareRecord;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface ShareRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Oct 19 12:54:26 CST 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Oct 19 12:54:26 CST 2018
     */
    int insert(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Oct 19 12:54:26 CST 2018
     */
    int insertSelective(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Oct 19 12:54:26 CST 2018
     */
    ShareRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Oct 19 12:54:26 CST 2018
     */
    int updateByPrimaryKeySelective(ShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_record
     *
     * @mbggenerated Fri Oct 19 12:54:26 CST 2018
     */
    int updateByPrimaryKey(ShareRecord record);


    List<Map<String,Object>> getShareRecords(@Param("userId") String userId, @Param("targetUserId") String targetUserId, @Param("effectiveTime") Date effectiveTime);


    ShareRecord getTargetShareRecord(@Param("userId") String userId, @Param("targetUserId") String targetUserId, @Param("effectiveTime") Date effectiveTime);

    List<Map<String,Object>> getTopShareRecords(@Param("userId") String userId, @Param("effectiveTime") Date effectiveTime);


}