package com.pokepet.dao;

import com.pokepet.model.UserFollow;

import java.util.List;
import java.util.Map;

public interface UserFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    int insert(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    int insertSelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    UserFollow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    int updateByPrimaryKeySelective(UserFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_follow
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    int updateByPrimaryKey(UserFollow record);

    /**
     * 获取用户关注数
     * @param userId
     * @return
     */
    int selectFollowAmount(String userId);


    /**
     * 获取用户粉丝数
     * @param userId
     * @return
     */
    int selectFollowedAmount(String userId);


    UserFollow selectFollowedUser(UserFollow userFollow);

    UserFollow selectExistFollowedUser(UserFollow userFollow);


    List<Map<String,String>> selectFollowers(String userId);

    List<Map<String,String>> selectFans(String userId);


}