package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import com.pokepet.model.UserLongRecord;

public interface UserLongRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Thu Sep 20 14:08:55 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Thu Sep 20 14:08:55 GMT+08:00 2018
     */
    int insert(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Thu Sep 20 14:08:55 GMT+08:00 2018
     */
    int insertSelective(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Thu Sep 20 14:08:55 GMT+08:00 2018
     */
    UserLongRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Thu Sep 20 14:08:55 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Thu Sep 20 14:08:55 GMT+08:00 2018
     */
    int updateByPrimaryKeyWithBLOBs(UserLongRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_long_record
     *
     * @mbggenerated Thu Sep 20 14:08:55 GMT+08:00 2018
     */
    int updateByPrimaryKey(UserLongRecord record);

	List<Map<String, Object>> selectLongRecordList(Map<String, Object> param);
}