package com.pokepet.dao;

import java.util.List;
import java.util.Map;

import com.pokepet.model.UserWalkHistory;

public interface UserWalkHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_walk_history
	 * 
	 * @mbggenerated Tue Jun 05 16:24:38 CST 2018
	 */
	int deleteByPrimaryKey(String historyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_walk_history
	 * 
	 * @mbggenerated Tue Jun 05 16:24:38 CST 2018
	 */
	int insert(UserWalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_walk_history
	 * 
	 * @mbggenerated Tue Jun 05 16:24:38 CST 2018
	 */
	int insertSelective(UserWalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_walk_history
	 * 
	 * @mbggenerated Tue Jun 05 16:24:38 CST 2018
	 */
	UserWalkHistory selectByPrimaryKey(String historyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_walk_history
	 * 
	 * @mbggenerated Tue Jun 05 16:24:38 CST 2018
	 */
	int updateByPrimaryKeySelective(UserWalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_walk_history
	 * 
	 * @mbggenerated Tue Jun 05 16:24:38 CST 2018
	 */
	int updateByPrimaryKey(UserWalkHistory record);

	List<UserWalkHistory> getHistoryListByUserId(String userId);

	int getWalkDistanceByUserId(String usersId);

	int getWalkDistanceByPetId(String petId);

	List<Map<String, Object>> getWalkAround(String userId, String longitude, String latitude, String minuteAgo,
			String disAround);
}