package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.UserShoppingAddress;

public interface UserShoppingAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    int insert(UserShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    int insertSelective(UserShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    UserShoppingAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserShoppingAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_shopping_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    int updateByPrimaryKey(UserShoppingAddress record);
    
    public List<UserShoppingAddress> getAddressList(String userId);
    
    public int resetDefultAddress(String userId);
}