package com.pokepet.dao;

import com.pokepet.model.UserTemp;

public interface UserTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_temp
     *
     * @mbggenerated Mon Nov 19 12:02:18 CST 2018
     */
    int deleteByPrimaryKey(String userTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_temp
     *
     * @mbggenerated Mon Nov 19 12:02:18 CST 2018
     */
    int insert(UserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_temp
     *
     * @mbggenerated Mon Nov 19 12:02:18 CST 2018
     */
    int insertSelective(UserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_temp
     *
     * @mbggenerated Mon Nov 19 12:02:18 CST 2018
     */
    UserTemp selectByPrimaryKey(String userTempId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_temp
     *
     * @mbggenerated Mon Nov 19 12:02:18 CST 2018
     */
    int updateByPrimaryKeySelective(UserTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_temp
     *
     * @mbggenerated Mon Nov 19 12:02:18 CST 2018
     */
    int updateByPrimaryKey(UserTemp record);

    UserTemp getTempUserByOpenId(String openId);
}