package com.pokepet.dao;

import com.pokepet.model.UserPaymentLog;

public interface UserPaymentLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Aug 10 11:55:26 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Aug 10 11:55:26 GMT+08:00 2018
     */
    int insert(UserPaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Aug 10 11:55:26 GMT+08:00 2018
     */
    int insertSelective(UserPaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Aug 10 11:55:26 GMT+08:00 2018
     */
    UserPaymentLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Aug 10 11:55:26 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(UserPaymentLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_payment_log
     *
     * @mbggenerated Fri Aug 10 11:55:26 GMT+08:00 2018
     */
    int updateByPrimaryKey(UserPaymentLog record);
}