package com.pokepet.dao;

import java.util.List;

import com.pokepet.model.UserWalkHistory;

public interface UserWalkHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_walk_history
	 * @mbggenerated  Tue Jun 05 16:24:38 CST 2018
	 */
	int deleteByPrimaryKey(String historyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_walk_history
	 * @mbggenerated  Tue Jun 05 16:24:38 CST 2018
	 */
	int insert(UserWalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_walk_history
	 * @mbggenerated  Tue Jun 05 16:24:38 CST 2018
	 */
	int insertSelective(UserWalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_walk_history
	 * @mbggenerated  Tue Jun 05 16:24:38 CST 2018
	 */
	UserWalkHistory selectByPrimaryKey(String historyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_walk_history
	 * @mbggenerated  Tue Jun 05 16:24:38 CST 2018
	 */
	int updateByPrimaryKeySelective(UserWalkHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_walk_history
	 * @mbggenerated  Tue Jun 05 16:24:38 CST 2018
	 */
	int updateByPrimaryKey(UserWalkHistory record);

	List<UserWalkHistory> getHistoryListByUserId(String userId);
	
	/**
	 * 
	 * @Description: 获取用户累计walk距离
	 * @param @param usersId
	 * @param @return   
	 * @return int  
	 * @throws
	 * @author Bean Zhou
	 * @date 2018年6月5日
	 */
	int getWalkDistanceByUserId(String usersId);
	
	/**
	 * 
	 * @Description: 获取pet累计walk距离
	 * @param @param petId
	 * @param @return   
	 * @return int  
	 * @throws
	 * @author Bean Zhou
	 * @date 2018年6月5日
	 */
	int getWalkDistanceByPetId(String petId);
}