package com.pokepet.dao;

import org.apache.ibatis.annotations.Param;

import com.pokepet.model.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Aug 08 18:21:31 GMT+08:00 2018
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Aug 08 18:21:31 GMT+08:00 2018
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Aug 08 18:21:31 GMT+08:00 2018
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Aug 08 18:21:31 GMT+08:00 2018
	 */
	User selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Aug 08 18:21:31 GMT+08:00 2018
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Wed Aug 08 18:21:31 GMT+08:00 2018
	 */
	int updateByPrimaryKey(User record);

	int getLit(String id);

	User getUserByOpenId(String openId);
	
	String getMaxUserNo(@Param("userIdStart") String userIdStart,@Param("year") String year);

	List<User> selectAllUsers(Map<String,Object> map);

	int selectAllUsersCount(Map<String,Object> map);
}