package com.pokepet.model;

import java.util.Date;

public class ActActivityRegister {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_register.register_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    private String registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_register.register_no
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    private Integer registerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_register.activity_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    private String activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_register.user_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_register.create_time
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_register.del_flag
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    private String delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_register.content
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_register.register_id
     *
     * @return the value of act_activity_register.register_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public String getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_register.register_id
     *
     * @param registerId the value for act_activity_register.register_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public void setRegisterId(String registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_register.register_no
     *
     * @return the value of act_activity_register.register_no
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public Integer getRegisterNo() {
        return registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_register.register_no
     *
     * @param registerNo the value for act_activity_register.register_no
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public void setRegisterNo(Integer registerNo) {
        this.registerNo = registerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_register.activity_id
     *
     * @return the value of act_activity_register.activity_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public String getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_register.activity_id
     *
     * @param activityId the value for act_activity_register.activity_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public void setActivityId(String activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_register.user_id
     *
     * @return the value of act_activity_register.user_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_register.user_id
     *
     * @param userId the value for act_activity_register.user_id
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_register.create_time
     *
     * @return the value of act_activity_register.create_time
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_register.create_time
     *
     * @param createTime the value for act_activity_register.create_time
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_register.del_flag
     *
     * @return the value of act_activity_register.del_flag
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_register.del_flag
     *
     * @param delFlag the value for act_activity_register.del_flag
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_register.content
     *
     * @return the value of act_activity_register.content
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_register.content
     *
     * @param content the value for act_activity_register.content
     *
     * @mbggenerated Sun Nov 04 13:36:48 GMT+08:00 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}