package com.pokepet.model;

import java.util.Date;

public class ActActivity {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.id
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.banner
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String banner;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.title
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.info
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String info;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.pic
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String pic;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.start_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private Date startTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.end_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private Date endTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.address
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.sponsor_logo
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String sponsorLogo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.sponsor_name
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String sponsorName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.sponsor_wx
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String sponsorWx;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.create_by
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String createBy;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.create_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.del_flag
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private String delFlag;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column act_activity.browse_amount
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	private Integer browseAmount;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.id
	 *
	 * @return the value of act_activity.id
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.id
	 *
	 * @param id the value for act_activity.id
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.banner
	 *
	 * @return the value of act_activity.banner
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getBanner() {
		return banner;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.banner
	 *
	 * @param banner the value for act_activity.banner
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setBanner(String banner) {
		this.banner = banner;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.title
	 *
	 * @return the value of act_activity.title
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.title
	 *
	 * @param title the value for act_activity.title
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.info
	 *
	 * @return the value of act_activity.info
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.info
	 *
	 * @param info the value for act_activity.info
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setInfo(String info) {
		this.info = info;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.pic
	 *
	 * @return the value of act_activity.pic
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.pic
	 *
	 * @param pic the value for act_activity.pic
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.start_time
	 *
	 * @return the value of act_activity.start_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.start_time
	 *
	 * @param startTime the value for act_activity.start_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.end_time
	 *
	 * @return the value of act_activity.end_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.end_time
	 *
	 * @param endTime the value for act_activity.end_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.address
	 *
	 * @return the value of act_activity.address
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.address
	 *
	 * @param address the value for act_activity.address
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.sponsor_logo
	 *
	 * @return the value of act_activity.sponsor_logo
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getSponsorLogo() {
		return sponsorLogo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.sponsor_logo
	 *
	 * @param sponsorLogo the value for act_activity.sponsor_logo
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setSponsorLogo(String sponsorLogo) {
		this.sponsorLogo = sponsorLogo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.sponsor_name
	 *
	 * @return the value of act_activity.sponsor_name
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getSponsorName() {
		return sponsorName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.sponsor_name
	 *
	 * @param sponsorName the value for act_activity.sponsor_name
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setSponsorName(String sponsorName) {
		this.sponsorName = sponsorName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.sponsor_wx
	 *
	 * @return the value of act_activity.sponsor_wx
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getSponsorWx() {
		return sponsorWx;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.sponsor_wx
	 *
	 * @param sponsorWx the value for act_activity.sponsor_wx
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setSponsorWx(String sponsorWx) {
		this.sponsorWx = sponsorWx;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.create_by
	 *
	 * @return the value of act_activity.create_by
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.create_by
	 *
	 * @param createBy the value for act_activity.create_by
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.create_time
	 *
	 * @return the value of act_activity.create_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.create_time
	 *
	 * @param createTime the value for act_activity.create_time
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.del_flag
	 *
	 * @return the value of act_activity.del_flag
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.del_flag
	 *
	 * @param delFlag the value for act_activity.del_flag
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column act_activity.browse_amount
	 *
	 * @return the value of act_activity.browse_amount
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public Integer getBrowseAmount() {
		return browseAmount;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column act_activity.browse_amount
	 *
	 * @param browseAmount the value for act_activity.browse_amount
	 *
	 * @mbggenerated Tue Nov 20 16:10:40 CST 2018
	 */
	public void setBrowseAmount(Integer browseAmount) {
		this.browseAmount = browseAmount;
	}
}