package com.pokepet.model;

import java.util.Date;

public class ActActivityGuestLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_guest_login.id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_guest_login.user_id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_guest_login.create_time
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column act_activity_guest_login.act_id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    private String actId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_guest_login.id
     *
     * @return the value of act_activity_guest_login.id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_guest_login.id
     *
     * @param id the value for act_activity_guest_login.id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_guest_login.user_id
     *
     * @return the value of act_activity_guest_login.user_id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_guest_login.user_id
     *
     * @param userId the value for act_activity_guest_login.user_id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_guest_login.create_time
     *
     * @return the value of act_activity_guest_login.create_time
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_guest_login.create_time
     *
     * @param createTime the value for act_activity_guest_login.create_time
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column act_activity_guest_login.act_id
     *
     * @return the value of act_activity_guest_login.act_id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public String getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column act_activity_guest_login.act_id
     *
     * @param actId the value for act_activity_guest_login.act_id
     *
     * @mbggenerated Tue Nov 13 21:54:39 CST 2018
     */
    public void setActId(String actId) {
        this.actId = actId;
    }
}