package com.pokepet.model;

import java.util.Date;

public class ActActivity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.id
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.title
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.info
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private String info;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.pic
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private String pic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.start_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.end_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.create_by
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private String createBy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.create_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column act_activity.del_flag
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.id
	 * @return  the value of act_activity.id
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.id
	 * @param id  the value for act_activity.id
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.title
	 * @return  the value of act_activity.title
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.title
	 * @param title  the value for act_activity.title
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.info
	 * @return  the value of act_activity.info
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.info
	 * @param info  the value for act_activity.info
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setInfo(String info) {
		this.info = info;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.pic
	 * @return  the value of act_activity.pic
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public String getPic() {
		return pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.pic
	 * @param pic  the value for act_activity.pic
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.start_time
	 * @return  the value of act_activity.start_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.start_time
	 * @param startTime  the value for act_activity.start_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.end_time
	 * @return  the value of act_activity.end_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.end_time
	 * @param endTime  the value for act_activity.end_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.create_by
	 * @return  the value of act_activity.create_by
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public String getCreateBy() {
		return createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.create_by
	 * @param createBy  the value for act_activity.create_by
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.create_time
	 * @return  the value of act_activity.create_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.create_time
	 * @param createTime  the value for act_activity.create_time
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column act_activity.del_flag
	 * @return  the value of act_activity.del_flag
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column act_activity.del_flag
	 * @param delFlag  the value for act_activity.del_flag
	 * @mbggenerated  Sun Nov 04 14:26:42 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}