package com.pokepet.model;

import java.util.Date;

public class CmsBanner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.banner_id
     *
     * @mbggenerated Tue Mar 12 19:12:47 CST 2019
     */
    private String bannerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.banner_img_url
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    private String bannerImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.banner_redirect_url
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    private String bannerRedirectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.effective_date
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    private Date effectiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.is_valid
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.create_time
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_banner.sort
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.banner_id
     *
     * @return the value of cms_banner.banner_id
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public String getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.banner_id
     *
     * @param bannerId the value for cms_banner.banner_id
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public void setBannerId(String bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.banner_img_url
     *
     * @return the value of cms_banner.banner_img_url
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public String getBannerImgUrl() {
        return bannerImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.banner_img_url
     *
     * @param bannerImgUrl the value for cms_banner.banner_img_url
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public void setBannerImgUrl(String bannerImgUrl) {
        this.bannerImgUrl = bannerImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.banner_redirect_url
     *
     * @return the value of cms_banner.banner_redirect_url
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public String getBannerRedirectUrl() {
        return bannerRedirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.banner_redirect_url
     *
     * @param bannerRedirectUrl the value for cms_banner.banner_redirect_url
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public void setBannerRedirectUrl(String bannerRedirectUrl) {
        this.bannerRedirectUrl = bannerRedirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.effective_date
     *
     * @return the value of cms_banner.effective_date
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public Date getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.effective_date
     *
     * @param effectiveDate the value for cms_banner.effective_date
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.is_valid
     *
     * @return the value of cms_banner.is_valid
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.is_valid
     *
     * @param isValid the value for cms_banner.is_valid
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.create_time
     *
     * @return the value of cms_banner.create_time
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.create_time
     *
     * @param createTime the value for cms_banner.create_time
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_banner.sort
     *
     * @return the value of cms_banner.sort
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_banner.sort
     *
     * @param sort the value for cms_banner.sort
     *
     * @mbggenerated Tue Mar 12 19:12:48 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}