package com.pokepet.model;

import java.util.Date;

public class Commodity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.commodity_id
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.commodity_name
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String commodityName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.commodity_describe
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String commodityDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.specification
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String specification;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.commodity_type
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String commodityType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.commodity_brand
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String commodityBrand;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.purchase_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Double purchasePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.sale_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Double salePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.discount
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Double discount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.inventory
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Integer inventory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.on_sale
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String onSale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.on_conversion
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String onConversion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.conversion_coin
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Integer conversionCoin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.conversion_ticket
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Integer conversionTicket;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.conversion_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Double conversionPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.sale_start_datetime
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Date saleStartDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.sale_end_datetime
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private Date saleEndDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.carousel_pic1
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String carouselPic1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.carousel_pic2
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String carouselPic2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.carousel_pic3
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String carouselPic3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.carousel_pic4
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String carouselPic4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.carousel_pic5
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String carouselPic5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.del_flag
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String delFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column commodity.detail
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	private String detail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.commodity_id
	 * @return  the value of commodity.commodity_id
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.commodity_id
	 * @param commodityId  the value for commodity.commodity_id
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.commodity_name
	 * @return  the value of commodity.commodity_name
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCommodityName() {
		return commodityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.commodity_name
	 * @param commodityName  the value for commodity.commodity_name
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCommodityName(String commodityName) {
		this.commodityName = commodityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.commodity_describe
	 * @return  the value of commodity.commodity_describe
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCommodityDescribe() {
		return commodityDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.commodity_describe
	 * @param commodityDescribe  the value for commodity.commodity_describe
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCommodityDescribe(String commodityDescribe) {
		this.commodityDescribe = commodityDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.specification
	 * @return  the value of commodity.specification
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getSpecification() {
		return specification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.specification
	 * @param specification  the value for commodity.specification
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setSpecification(String specification) {
		this.specification = specification;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.commodity_type
	 * @return  the value of commodity.commodity_type
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCommodityType() {
		return commodityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.commodity_type
	 * @param commodityType  the value for commodity.commodity_type
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCommodityType(String commodityType) {
		this.commodityType = commodityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.commodity_brand
	 * @return  the value of commodity.commodity_brand
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCommodityBrand() {
		return commodityBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.commodity_brand
	 * @param commodityBrand  the value for commodity.commodity_brand
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCommodityBrand(String commodityBrand) {
		this.commodityBrand = commodityBrand;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.price
	 * @return  the value of commodity.price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.price
	 * @param price  the value for commodity.price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.purchase_price
	 * @return  the value of commodity.purchase_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Double getPurchasePrice() {
		return purchasePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.purchase_price
	 * @param purchasePrice  the value for commodity.purchase_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setPurchasePrice(Double purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.sale_price
	 * @return  the value of commodity.sale_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Double getSalePrice() {
		return salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.sale_price
	 * @param salePrice  the value for commodity.sale_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.discount
	 * @return  the value of commodity.discount
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Double getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.discount
	 * @param discount  the value for commodity.discount
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.inventory
	 * @return  the value of commodity.inventory
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Integer getInventory() {
		return inventory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.inventory
	 * @param inventory  the value for commodity.inventory
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setInventory(Integer inventory) {
		this.inventory = inventory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.on_sale
	 * @return  the value of commodity.on_sale
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getOnSale() {
		return onSale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.on_sale
	 * @param onSale  the value for commodity.on_sale
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setOnSale(String onSale) {
		this.onSale = onSale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.on_conversion
	 * @return  the value of commodity.on_conversion
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getOnConversion() {
		return onConversion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.on_conversion
	 * @param onConversion  the value for commodity.on_conversion
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setOnConversion(String onConversion) {
		this.onConversion = onConversion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.conversion_coin
	 * @return  the value of commodity.conversion_coin
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Integer getConversionCoin() {
		return conversionCoin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.conversion_coin
	 * @param conversionCoin  the value for commodity.conversion_coin
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setConversionCoin(Integer conversionCoin) {
		this.conversionCoin = conversionCoin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.conversion_ticket
	 * @return  the value of commodity.conversion_ticket
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Integer getConversionTicket() {
		return conversionTicket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.conversion_ticket
	 * @param conversionTicket  the value for commodity.conversion_ticket
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setConversionTicket(Integer conversionTicket) {
		this.conversionTicket = conversionTicket;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.conversion_price
	 * @return  the value of commodity.conversion_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Double getConversionPrice() {
		return conversionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.conversion_price
	 * @param conversionPrice  the value for commodity.conversion_price
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setConversionPrice(Double conversionPrice) {
		this.conversionPrice = conversionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.sale_start_datetime
	 * @return  the value of commodity.sale_start_datetime
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Date getSaleStartDatetime() {
		return saleStartDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.sale_start_datetime
	 * @param saleStartDatetime  the value for commodity.sale_start_datetime
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setSaleStartDatetime(Date saleStartDatetime) {
		this.saleStartDatetime = saleStartDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.sale_end_datetime
	 * @return  the value of commodity.sale_end_datetime
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public Date getSaleEndDatetime() {
		return saleEndDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.sale_end_datetime
	 * @param saleEndDatetime  the value for commodity.sale_end_datetime
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setSaleEndDatetime(Date saleEndDatetime) {
		this.saleEndDatetime = saleEndDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.carousel_pic1
	 * @return  the value of commodity.carousel_pic1
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCarouselPic1() {
		return carouselPic1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.carousel_pic1
	 * @param carouselPic1  the value for commodity.carousel_pic1
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCarouselPic1(String carouselPic1) {
		this.carouselPic1 = carouselPic1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.carousel_pic2
	 * @return  the value of commodity.carousel_pic2
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCarouselPic2() {
		return carouselPic2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.carousel_pic2
	 * @param carouselPic2  the value for commodity.carousel_pic2
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCarouselPic2(String carouselPic2) {
		this.carouselPic2 = carouselPic2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.carousel_pic3
	 * @return  the value of commodity.carousel_pic3
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCarouselPic3() {
		return carouselPic3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.carousel_pic3
	 * @param carouselPic3  the value for commodity.carousel_pic3
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCarouselPic3(String carouselPic3) {
		this.carouselPic3 = carouselPic3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.carousel_pic4
	 * @return  the value of commodity.carousel_pic4
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCarouselPic4() {
		return carouselPic4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.carousel_pic4
	 * @param carouselPic4  the value for commodity.carousel_pic4
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCarouselPic4(String carouselPic4) {
		this.carouselPic4 = carouselPic4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.carousel_pic5
	 * @return  the value of commodity.carousel_pic5
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getCarouselPic5() {
		return carouselPic5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.carousel_pic5
	 * @param carouselPic5  the value for commodity.carousel_pic5
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setCarouselPic5(String carouselPic5) {
		this.carouselPic5 = carouselPic5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.del_flag
	 * @return  the value of commodity.del_flag
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.del_flag
	 * @param delFlag  the value for commodity.del_flag
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column commodity.detail
	 * @return  the value of commodity.detail
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column commodity.detail
	 * @param detail  the value for commodity.detail
	 * @mbggenerated  Wed Oct 10 17:46:09 GMT+08:00 2018
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}
}