package com.pokepet.model;

public class ExplorePoint {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column explore_point.point_id
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	private String pointId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column explore_point.point_name
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	private String pointName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column explore_point.point_star
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	private Integer pointStar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column explore_point.point_intro
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	private String pointIntro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column explore_point.point_img
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	private String pointImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column explore_point.del_flag
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column explore_point.point_id
	 * @return  the value of explore_point.point_id
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public String getPointId() {
		return pointId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column explore_point.point_id
	 * @param pointId  the value for explore_point.point_id
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public void setPointId(String pointId) {
		this.pointId = pointId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column explore_point.point_name
	 * @return  the value of explore_point.point_name
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public String getPointName() {
		return pointName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column explore_point.point_name
	 * @param pointName  the value for explore_point.point_name
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public void setPointName(String pointName) {
		this.pointName = pointName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column explore_point.point_star
	 * @return  the value of explore_point.point_star
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public Integer getPointStar() {
		return pointStar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column explore_point.point_star
	 * @param pointStar  the value for explore_point.point_star
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public void setPointStar(Integer pointStar) {
		this.pointStar = pointStar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column explore_point.point_intro
	 * @return  the value of explore_point.point_intro
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public String getPointIntro() {
		return pointIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column explore_point.point_intro
	 * @param pointIntro  the value for explore_point.point_intro
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public void setPointIntro(String pointIntro) {
		this.pointIntro = pointIntro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column explore_point.point_img
	 * @return  the value of explore_point.point_img
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public String getPointImg() {
		return pointImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column explore_point.point_img
	 * @param pointImg  the value for explore_point.point_img
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public void setPointImg(String pointImg) {
		this.pointImg = pointImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column explore_point.del_flag
	 * @return  the value of explore_point.del_flag
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column explore_point.del_flag
	 * @param delFlag  the value for explore_point.del_flag
	 * @mbggenerated  Tue Aug 07 17:09:45 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}