package com.pokepet.model;

import java.util.Date;

public class MessageQueue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.message_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    private String messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.type
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.sender_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    private String senderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.receiver_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.message_content
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.read_state
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    private String readState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_queue.create_time
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.message_id
     *
     * @return the value of message_queue.message_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.message_id
     *
     * @param messageId the value for message_queue.message_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.type
     *
     * @return the value of message_queue.type
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.type
     *
     * @param type the value for message_queue.type
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.sender_id
     *
     * @return the value of message_queue.sender_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.sender_id
     *
     * @param senderId the value for message_queue.sender_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.receiver_id
     *
     * @return the value of message_queue.receiver_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.receiver_id
     *
     * @param receiverId the value for message_queue.receiver_id
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.message_content
     *
     * @return the value of message_queue.message_content
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.message_content
     *
     * @param messageContent the value for message_queue.message_content
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.read_state
     *
     * @return the value of message_queue.read_state
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public String getReadState() {
        return readState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.read_state
     *
     * @param readState the value for message_queue.read_state
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public void setReadState(String readState) {
        this.readState = readState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_queue.create_time
     *
     * @return the value of message_queue.create_time
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_queue.create_time
     *
     * @param createTime the value for message_queue.create_time
     *
     * @mbggenerated Mon Oct 15 21:09:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}