package com.pokepet.model;

import java.util.Date;

public class OrderMall {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.order_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.commodity_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String commodityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.commodity_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String commodityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.user_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.address_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.buy_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String buyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.money
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.coin
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private Integer coin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.pay_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.pay_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.create_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.effective_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private Date effectiveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.order_status
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.order_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_mall.del_flag
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.order_id
     *
     * @return the value of order_mall.order_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.order_id
     *
     * @param orderId the value for order_mall.order_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.commodity_id
     *
     * @return the value of order_mall.commodity_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.commodity_id
     *
     * @param commodityId the value for order_mall.commodity_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setCommodityId(String commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.commodity_type
     *
     * @return the value of order_mall.commodity_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getCommodityType() {
        return commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.commodity_type
     *
     * @param commodityType the value for order_mall.commodity_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setCommodityType(String commodityType) {
        this.commodityType = commodityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.user_id
     *
     * @return the value of order_mall.user_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.user_id
     *
     * @param userId the value for order_mall.user_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.address_id
     *
     * @return the value of order_mall.address_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.address_id
     *
     * @param addressId the value for order_mall.address_id
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.buy_type
     *
     * @return the value of order_mall.buy_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getBuyType() {
        return buyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.buy_type
     *
     * @param buyType the value for order_mall.buy_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setBuyType(String buyType) {
        this.buyType = buyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.money
     *
     * @return the value of order_mall.money
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.money
     *
     * @param money the value for order_mall.money
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.coin
     *
     * @return the value of order_mall.coin
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public Integer getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.coin
     *
     * @param coin the value for order_mall.coin
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setCoin(Integer coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.pay_type
     *
     * @return the value of order_mall.pay_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.pay_type
     *
     * @param payType the value for order_mall.pay_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.pay_time
     *
     * @return the value of order_mall.pay_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.pay_time
     *
     * @param payTime the value for order_mall.pay_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.create_time
     *
     * @return the value of order_mall.create_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.create_time
     *
     * @param createTime the value for order_mall.create_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.effective_time
     *
     * @return the value of order_mall.effective_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public Date getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.effective_time
     *
     * @param effectiveTime the value for order_mall.effective_time
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setEffectiveTime(Date effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.order_status
     *
     * @return the value of order_mall.order_status
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.order_status
     *
     * @param orderStatus the value for order_mall.order_status
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.order_type
     *
     * @return the value of order_mall.order_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.order_type
     *
     * @param orderType the value for order_mall.order_type
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_mall.del_flag
     *
     * @return the value of order_mall.del_flag
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_mall.del_flag
     *
     * @param delFlag the value for order_mall.del_flag
     *
     * @mbggenerated Thu Oct 11 14:15:57 GMT+08:00 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}