package com.pokepet.model;

import java.util.Date;

public class OrderPay {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.order_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.commodity_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String commodityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.commodity_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String commodityType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.user_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.address_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String addressId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.price
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.pay_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.pay_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.create_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.effective_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private Date effectiveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.order_status
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.order_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_pay.del_flag
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.order_id
	 * @return  the value of order_pay.order_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.order_id
	 * @param orderId  the value for order_pay.order_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.commodity_id
	 * @return  the value of order_pay.commodity_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getCommodityId() {
		return commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.commodity_id
	 * @param commodityId  the value for order_pay.commodity_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setCommodityId(String commodityId) {
		this.commodityId = commodityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.commodity_type
	 * @return  the value of order_pay.commodity_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getCommodityType() {
		return commodityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.commodity_type
	 * @param commodityType  the value for order_pay.commodity_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setCommodityType(String commodityType) {
		this.commodityType = commodityType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.user_id
	 * @return  the value of order_pay.user_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.user_id
	 * @param userId  the value for order_pay.user_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.address_id
	 * @return  the value of order_pay.address_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getAddressId() {
		return addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.address_id
	 * @param addressId  the value for order_pay.address_id
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.price
	 * @return  the value of order_pay.price
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.price
	 * @param price  the value for order_pay.price
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.pay_type
	 * @return  the value of order_pay.pay_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.pay_type
	 * @param payType  the value for order_pay.pay_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setPayType(String payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.pay_time
	 * @return  the value of order_pay.pay_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.pay_time
	 * @param payTime  the value for order_pay.pay_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.create_time
	 * @return  the value of order_pay.create_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.create_time
	 * @param createTime  the value for order_pay.create_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.effective_time
	 * @return  the value of order_pay.effective_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public Date getEffectiveTime() {
		return effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.effective_time
	 * @param effectiveTime  the value for order_pay.effective_time
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setEffectiveTime(Date effectiveTime) {
		this.effectiveTime = effectiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.order_status
	 * @return  the value of order_pay.order_status
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.order_status
	 * @param orderStatus  the value for order_pay.order_status
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.order_type
	 * @return  the value of order_pay.order_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.order_type
	 * @param orderType  the value for order_pay.order_type
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_pay.del_flag
	 * @return  the value of order_pay.del_flag
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_pay.del_flag
	 * @param delFlag  the value for order_pay.del_flag
	 * @mbggenerated  Wed Oct 10 17:45:57 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}
