package com.pokepet.model;

import java.util.Date;

public class Pet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.pet_id
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String petId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.species
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String species;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.name
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.sex
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.birthday
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private Date birthday;

	private String age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.weight
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String weight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.photo_path
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String photoPath;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.sterilization
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String sterilization;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.level
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.energy_coin
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private Integer energyCoin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.exp
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private Integer exp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet.del_flag
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	private String delFlag;

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.pet_id
	 * @return  the value of pet.pet_id
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getPetId() {
		return petId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.pet_id
	 * @param petId  the value for pet.pet_id
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setPetId(String petId) {
		this.petId = petId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.species
	 * @return  the value of pet.species
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getSpecies() {
		return species;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.species
	 * @param species  the value for pet.species
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setSpecies(String species) {
		this.species = species;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.name
	 * @return  the value of pet.name
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.name
	 * @param name  the value for pet.name
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.sex
	 * @return  the value of pet.sex
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.sex
	 * @param sex  the value for pet.sex
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.birthday
	 * @return  the value of pet.birthday
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.birthday
	 * @param birthday  the value for pet.birthday
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.weight
	 * @return  the value of pet.weight
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.weight
	 * @param weight  the value for pet.weight
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setWeight(String weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.photo_path
	 * @return  the value of pet.photo_path
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getPhotoPath() {
		return photoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.photo_path
	 * @param photoPath  the value for pet.photo_path
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setPhotoPath(String photoPath) {
		this.photoPath = photoPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.sterilization
	 * @return  the value of pet.sterilization
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getSterilization() {
		return sterilization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.sterilization
	 * @param sterilization  the value for pet.sterilization
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setSterilization(String sterilization) {
		this.sterilization = sterilization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.level
	 * @return  the value of pet.level
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.level
	 * @param level  the value for pet.level
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.energy_coin
	 * @return  the value of pet.energy_coin
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public Integer getEnergyCoin() {
		return energyCoin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.energy_coin
	 * @param energyCoin  the value for pet.energy_coin
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setEnergyCoin(Integer energyCoin) {
		this.energyCoin = energyCoin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.exp
	 * @return  the value of pet.exp
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public Integer getExp() {
		return exp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.exp
	 * @param exp  the value for pet.exp
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setExp(Integer exp) {
		this.exp = exp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet.del_flag
	 * @return  the value of pet.del_flag
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet.del_flag
	 * @param delFlag  the value for pet.del_flag
	 * @mbggenerated  Sat Jul 07 16:34:44 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}