package com.pokepet.model;

import java.util.Date;

public class PetRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.record_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.title
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.user_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.pet_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String petId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.create_time
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.check_state
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String checkState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.del_state
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String delState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.abbre_img
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String abbreImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pet_record.content
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    private String content;

    private String showTime;

    public String getShowTime() {
        return showTime;
    }

    public void setShowTime(String showTime) {
        this.showTime = showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.record_id
     *
     * @return the value of pet_record.record_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.record_id
     *
     * @param recordId the value for pet_record.record_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.title
     *
     * @return the value of pet_record.title
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.title
     *
     * @param title the value for pet_record.title
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.user_id
     *
     * @return the value of pet_record.user_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.user_id
     *
     * @param userId the value for pet_record.user_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.pet_id
     *
     * @return the value of pet_record.pet_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.pet_id
     *
     * @param petId the value for pet_record.pet_id
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.create_time
     *
     * @return the value of pet_record.create_time
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.create_time
     *
     * @param createTime the value for pet_record.create_time
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.check_state
     *
     * @return the value of pet_record.check_state
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getCheckState() {
        return checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.check_state
     *
     * @param checkState the value for pet_record.check_state
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setCheckState(String checkState) {
        this.checkState = checkState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.del_state
     *
     * @return the value of pet_record.del_state
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.del_state
     *
     * @param delState the value for pet_record.del_state
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.abbre_img
     *
     * @return the value of pet_record.abbre_img
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getAbbreImg() {
        return abbreImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.abbre_img
     *
     * @param abbreImg the value for pet_record.abbre_img
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setAbbreImg(String abbreImg) {
        this.abbreImg = abbreImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pet_record.content
     *
     * @return the value of pet_record.content
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pet_record.content
     *
     * @param content the value for pet_record.content
     *
     * @mbggenerated Tue Sep 11 15:14:56 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}