package com.pokepet.model;

public class PetSupply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.supply_id
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private String supplyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.supply_type
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private String supplyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.supply_img
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private String supplyImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.supply_name
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private String supplyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.supply_demand_level
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private Integer supplyDemandLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.supply_rare_degree
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private Integer supplyRareDegree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.add_energy
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private Integer addEnergy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.supply_description
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private String supplyDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.buy_money
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private Integer buyMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.buy_chip
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private Integer buyChip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_supply.del_flag
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.supply_id
	 * @return  the value of pet_supply.supply_id
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public String getSupplyId() {
		return supplyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.supply_id
	 * @param supplyId  the value for pet_supply.supply_id
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setSupplyId(String supplyId) {
		this.supplyId = supplyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.supply_type
	 * @return  the value of pet_supply.supply_type
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public String getSupplyType() {
		return supplyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.supply_type
	 * @param supplyType  the value for pet_supply.supply_type
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setSupplyType(String supplyType) {
		this.supplyType = supplyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.supply_img
	 * @return  the value of pet_supply.supply_img
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public String getSupplyImg() {
		return supplyImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.supply_img
	 * @param supplyImg  the value for pet_supply.supply_img
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setSupplyImg(String supplyImg) {
		this.supplyImg = supplyImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.supply_name
	 * @return  the value of pet_supply.supply_name
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public String getSupplyName() {
		return supplyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.supply_name
	 * @param supplyName  the value for pet_supply.supply_name
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setSupplyName(String supplyName) {
		this.supplyName = supplyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.supply_demand_level
	 * @return  the value of pet_supply.supply_demand_level
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public Integer getSupplyDemandLevel() {
		return supplyDemandLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.supply_demand_level
	 * @param supplyDemandLevel  the value for pet_supply.supply_demand_level
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setSupplyDemandLevel(Integer supplyDemandLevel) {
		this.supplyDemandLevel = supplyDemandLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.supply_rare_degree
	 * @return  the value of pet_supply.supply_rare_degree
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public Integer getSupplyRareDegree() {
		return supplyRareDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.supply_rare_degree
	 * @param supplyRareDegree  the value for pet_supply.supply_rare_degree
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setSupplyRareDegree(Integer supplyRareDegree) {
		this.supplyRareDegree = supplyRareDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.add_energy
	 * @return  the value of pet_supply.add_energy
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public Integer getAddEnergy() {
		return addEnergy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.add_energy
	 * @param addEnergy  the value for pet_supply.add_energy
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setAddEnergy(Integer addEnergy) {
		this.addEnergy = addEnergy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.supply_description
	 * @return  the value of pet_supply.supply_description
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public String getSupplyDescription() {
		return supplyDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.supply_description
	 * @param supplyDescription  the value for pet_supply.supply_description
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setSupplyDescription(String supplyDescription) {
		this.supplyDescription = supplyDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.buy_money
	 * @return  the value of pet_supply.buy_money
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public Integer getBuyMoney() {
		return buyMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.buy_money
	 * @param buyMoney  the value for pet_supply.buy_money
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setBuyMoney(Integer buyMoney) {
		this.buyMoney = buyMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.buy_chip
	 * @return  the value of pet_supply.buy_chip
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public Integer getBuyChip() {
		return buyChip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.buy_chip
	 * @param buyChip  the value for pet_supply.buy_chip
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setBuyChip(Integer buyChip) {
		this.buyChip = buyChip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_supply.del_flag
	 * @return  the value of pet_supply.del_flag
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_supply.del_flag
	 * @param delFlag  the value for pet_supply.del_flag
	 * @mbggenerated  Thu Aug 09 16:28:02 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}