package com.pokepet.model;

public class PetWeapon {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_id
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private String weaponId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_name
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private String weaponName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_img
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private String weaponImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_demand_level
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private Integer weaponDemandLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_rare_degree
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private Integer weaponRareDegree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_description
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private String weaponDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_install_state
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private String weaponInstallState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.chip_rate
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private Integer chipRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.chip_add_rate
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private Integer chipAddRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.chip_add_count
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private Integer chipAddCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.del_flag
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_id
	 * @return  the value of pet_weapon.weapon_id
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public String getWeaponId() {
		return weaponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_id
	 * @param weaponId  the value for pet_weapon.weapon_id
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setWeaponId(String weaponId) {
		this.weaponId = weaponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_name
	 * @return  the value of pet_weapon.weapon_name
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public String getWeaponName() {
		return weaponName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_name
	 * @param weaponName  the value for pet_weapon.weapon_name
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setWeaponName(String weaponName) {
		this.weaponName = weaponName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_img
	 * @return  the value of pet_weapon.weapon_img
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public String getWeaponImg() {
		return weaponImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_img
	 * @param weaponImg  the value for pet_weapon.weapon_img
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setWeaponImg(String weaponImg) {
		this.weaponImg = weaponImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_demand_level
	 * @return  the value of pet_weapon.weapon_demand_level
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public Integer getWeaponDemandLevel() {
		return weaponDemandLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_demand_level
	 * @param weaponDemandLevel  the value for pet_weapon.weapon_demand_level
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setWeaponDemandLevel(Integer weaponDemandLevel) {
		this.weaponDemandLevel = weaponDemandLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_rare_degree
	 * @return  the value of pet_weapon.weapon_rare_degree
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public Integer getWeaponRareDegree() {
		return weaponRareDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_rare_degree
	 * @param weaponRareDegree  the value for pet_weapon.weapon_rare_degree
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setWeaponRareDegree(Integer weaponRareDegree) {
		this.weaponRareDegree = weaponRareDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_description
	 * @return  the value of pet_weapon.weapon_description
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public String getWeaponDescription() {
		return weaponDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_description
	 * @param weaponDescription  the value for pet_weapon.weapon_description
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setWeaponDescription(String weaponDescription) {
		this.weaponDescription = weaponDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_install_state
	 * @return  the value of pet_weapon.weapon_install_state
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public String getWeaponInstallState() {
		return weaponInstallState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_install_state
	 * @param weaponInstallState  the value for pet_weapon.weapon_install_state
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setWeaponInstallState(String weaponInstallState) {
		this.weaponInstallState = weaponInstallState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.chip_rate
	 * @return  the value of pet_weapon.chip_rate
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public Integer getChipRate() {
		return chipRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.chip_rate
	 * @param chipRate  the value for pet_weapon.chip_rate
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setChipRate(Integer chipRate) {
		this.chipRate = chipRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.chip_add_rate
	 * @return  the value of pet_weapon.chip_add_rate
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public Integer getChipAddRate() {
		return chipAddRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.chip_add_rate
	 * @param chipAddRate  the value for pet_weapon.chip_add_rate
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setChipAddRate(Integer chipAddRate) {
		this.chipAddRate = chipAddRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.chip_add_count
	 * @return  the value of pet_weapon.chip_add_count
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public Integer getChipAddCount() {
		return chipAddCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.chip_add_count
	 * @param chipAddCount  the value for pet_weapon.chip_add_count
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setChipAddCount(Integer chipAddCount) {
		this.chipAddCount = chipAddCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.del_flag
	 * @return  the value of pet_weapon.del_flag
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.del_flag
	 * @param delFlag  the value for pet_weapon.del_flag
	 * @mbggenerated  Mon Aug 06 15:33:02 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}