package com.pokepet.model;

public class PetWeapon {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_id
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private String weaponId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_name
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private String weaponName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_img
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private String weaponImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_demand_level
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer weaponDemandLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_rare_degree
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer weaponRareDegree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_description
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private String weaponDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.chip_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer chipRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.chip_add_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer chipAddRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.chip_add_count
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer chipAddCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.weapon_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer weaponRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.supply_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer supplyRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.buy_money
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer buyMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.buy_chip
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private Integer buyChip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon.del_flag
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_id
	 * @return  the value of pet_weapon.weapon_id
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public String getWeaponId() {
		return weaponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_id
	 * @param weaponId  the value for pet_weapon.weapon_id
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setWeaponId(String weaponId) {
		this.weaponId = weaponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_name
	 * @return  the value of pet_weapon.weapon_name
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public String getWeaponName() {
		return weaponName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_name
	 * @param weaponName  the value for pet_weapon.weapon_name
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setWeaponName(String weaponName) {
		this.weaponName = weaponName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_img
	 * @return  the value of pet_weapon.weapon_img
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public String getWeaponImg() {
		return weaponImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_img
	 * @param weaponImg  the value for pet_weapon.weapon_img
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setWeaponImg(String weaponImg) {
		this.weaponImg = weaponImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_demand_level
	 * @return  the value of pet_weapon.weapon_demand_level
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getWeaponDemandLevel() {
		return weaponDemandLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_demand_level
	 * @param weaponDemandLevel  the value for pet_weapon.weapon_demand_level
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setWeaponDemandLevel(Integer weaponDemandLevel) {
		this.weaponDemandLevel = weaponDemandLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_rare_degree
	 * @return  the value of pet_weapon.weapon_rare_degree
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getWeaponRareDegree() {
		return weaponRareDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_rare_degree
	 * @param weaponRareDegree  the value for pet_weapon.weapon_rare_degree
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setWeaponRareDegree(Integer weaponRareDegree) {
		this.weaponRareDegree = weaponRareDegree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_description
	 * @return  the value of pet_weapon.weapon_description
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public String getWeaponDescription() {
		return weaponDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_description
	 * @param weaponDescription  the value for pet_weapon.weapon_description
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setWeaponDescription(String weaponDescription) {
		this.weaponDescription = weaponDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.chip_rate
	 * @return  the value of pet_weapon.chip_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getChipRate() {
		return chipRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.chip_rate
	 * @param chipRate  the value for pet_weapon.chip_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setChipRate(Integer chipRate) {
		this.chipRate = chipRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.chip_add_rate
	 * @return  the value of pet_weapon.chip_add_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getChipAddRate() {
		return chipAddRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.chip_add_rate
	 * @param chipAddRate  the value for pet_weapon.chip_add_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setChipAddRate(Integer chipAddRate) {
		this.chipAddRate = chipAddRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.chip_add_count
	 * @return  the value of pet_weapon.chip_add_count
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getChipAddCount() {
		return chipAddCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.chip_add_count
	 * @param chipAddCount  the value for pet_weapon.chip_add_count
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setChipAddCount(Integer chipAddCount) {
		this.chipAddCount = chipAddCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.weapon_rate
	 * @return  the value of pet_weapon.weapon_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getWeaponRate() {
		return weaponRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.weapon_rate
	 * @param weaponRate  the value for pet_weapon.weapon_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setWeaponRate(Integer weaponRate) {
		this.weaponRate = weaponRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.supply_rate
	 * @return  the value of pet_weapon.supply_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getSupplyRate() {
		return supplyRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.supply_rate
	 * @param supplyRate  the value for pet_weapon.supply_rate
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setSupplyRate(Integer supplyRate) {
		this.supplyRate = supplyRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.buy_money
	 * @return  the value of pet_weapon.buy_money
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getBuyMoney() {
		return buyMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.buy_money
	 * @param buyMoney  the value for pet_weapon.buy_money
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setBuyMoney(Integer buyMoney) {
		this.buyMoney = buyMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.buy_chip
	 * @return  the value of pet_weapon.buy_chip
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public Integer getBuyChip() {
		return buyChip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.buy_chip
	 * @param buyChip  the value for pet_weapon.buy_chip
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setBuyChip(Integer buyChip) {
		this.buyChip = buyChip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon.del_flag
	 * @return  the value of pet_weapon.del_flag
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon.del_flag
	 * @param delFlag  the value for pet_weapon.del_flag
	 * @mbggenerated  Thu Aug 09 15:05:18 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}