package com.pokepet.model;

public class PetWeaponConcat {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.weapon_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private String weaponId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.weapon_endurance_percent
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private Integer weaponEndurancePercent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.weapon_match_percent
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private Integer weaponMatchPercent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.weapon_install_state
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private String weaponInstallState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.weapon_status
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private String weaponStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.pet_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private String petId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.user_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pet_weapon_concat.del_flag
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.id
	 * @return  the value of pet_weapon_concat.id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.id
	 * @param id  the value for pet_weapon_concat.id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.weapon_id
	 * @return  the value of pet_weapon_concat.weapon_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public String getWeaponId() {
		return weaponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.weapon_id
	 * @param weaponId  the value for pet_weapon_concat.weapon_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setWeaponId(String weaponId) {
		this.weaponId = weaponId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.weapon_endurance_percent
	 * @return  the value of pet_weapon_concat.weapon_endurance_percent
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public Integer getWeaponEndurancePercent() {
		return weaponEndurancePercent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.weapon_endurance_percent
	 * @param weaponEndurancePercent  the value for pet_weapon_concat.weapon_endurance_percent
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setWeaponEndurancePercent(Integer weaponEndurancePercent) {
		this.weaponEndurancePercent = weaponEndurancePercent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.weapon_match_percent
	 * @return  the value of pet_weapon_concat.weapon_match_percent
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public Integer getWeaponMatchPercent() {
		return weaponMatchPercent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.weapon_match_percent
	 * @param weaponMatchPercent  the value for pet_weapon_concat.weapon_match_percent
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setWeaponMatchPercent(Integer weaponMatchPercent) {
		this.weaponMatchPercent = weaponMatchPercent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.weapon_install_state
	 * @return  the value of pet_weapon_concat.weapon_install_state
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public String getWeaponInstallState() {
		return weaponInstallState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.weapon_install_state
	 * @param weaponInstallState  the value for pet_weapon_concat.weapon_install_state
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setWeaponInstallState(String weaponInstallState) {
		this.weaponInstallState = weaponInstallState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.weapon_status
	 * @return  the value of pet_weapon_concat.weapon_status
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public String getWeaponStatus() {
		return weaponStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.weapon_status
	 * @param weaponStatus  the value for pet_weapon_concat.weapon_status
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setWeaponStatus(String weaponStatus) {
		this.weaponStatus = weaponStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.pet_id
	 * @return  the value of pet_weapon_concat.pet_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public String getPetId() {
		return petId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.pet_id
	 * @param petId  the value for pet_weapon_concat.pet_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setPetId(String petId) {
		this.petId = petId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.user_id
	 * @return  the value of pet_weapon_concat.user_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.user_id
	 * @param userId  the value for pet_weapon_concat.user_id
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pet_weapon_concat.del_flag
	 * @return  the value of pet_weapon_concat.del_flag
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pet_weapon_concat.del_flag
	 * @param delFlag  the value for pet_weapon_concat.del_flag
	 * @mbggenerated  Tue Aug 07 13:22:20 GMT+08:00 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}