package com.pokepet.model;

import java.util.Date;

public class RecordVisit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_visit.id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_visit.record_id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    private String recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_visit.record_type
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    private String recordType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_visit.user_id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_visit.create_time
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_visit.del_flag
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_visit.id
     *
     * @return the value of record_visit.id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_visit.id
     *
     * @param id the value for record_visit.id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_visit.record_id
     *
     * @return the value of record_visit.record_id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_visit.record_id
     *
     * @param recordId the value for record_visit.record_id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_visit.record_type
     *
     * @return the value of record_visit.record_type
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_visit.record_type
     *
     * @param recordType the value for record_visit.record_type
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public void setRecordType(String recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_visit.user_id
     *
     * @return the value of record_visit.user_id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_visit.user_id
     *
     * @param userId the value for record_visit.user_id
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_visit.create_time
     *
     * @return the value of record_visit.create_time
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_visit.create_time
     *
     * @param createTime the value for record_visit.create_time
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_visit.del_flag
     *
     * @return the value of record_visit.del_flag
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_visit.del_flag
     *
     * @param delFlag the value for record_visit.del_flag
     *
     * @mbggenerated Wed Nov 14 15:14:40 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}