package com.pokepet.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_phone
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.photo_path
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private String photoPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_datetime
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.union_id
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.del_flag
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.chip_count
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    private Integer chipCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_phone
     *
     * @return the value of user.mobile_phone
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_phone
     *
     * @param mobilePhone the value for user.mobile_phone
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.photo_path
     *
     * @return the value of user.photo_path
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.photo_path
     *
     * @param photoPath the value for user.photo_path
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_datetime
     *
     * @return the value of user.create_datetime
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_datetime
     *
     * @param createDatetime the value for user.create_datetime
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.union_id
     *
     * @return the value of user.union_id
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.union_id
     *
     * @param unionId the value for user.union_id
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.del_flag
     *
     * @return the value of user.del_flag
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.del_flag
     *
     * @param delFlag the value for user.del_flag
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.chip_count
     *
     * @return the value of user.chip_count
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public Integer getChipCount() {
        return chipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.chip_count
     *
     * @param chipCount the value for user.chip_count
     *
     * @mbggenerated Mon Nov 19 12:00:52 CST 2018
     */
    public void setChipCount(Integer chipCount) {
        this.chipCount = chipCount;
    }
}