package com.pokepet.model;

import java.util.Date;

public class UserLongRecord {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.record_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String recordId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.title
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String title;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.abbre_img
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String abbreImg;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.user_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String userId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.pet_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String petId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.create_time
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.check_state
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String checkState;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.type
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.check_by
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String checkBy;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.check_datetime
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private Date checkDatetime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.del_flag
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String delFlag;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.memo
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String memo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.recommend
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String recommend;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column user_long_record.content
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.record_id
	 *
	 * @return the value of user_long_record.record_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.record_id
	 *
	 * @param recordId the value for user_long_record.record_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.title
	 *
	 * @return the value of user_long_record.title
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.title
	 *
	 * @param title the value for user_long_record.title
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.abbre_img
	 *
	 * @return the value of user_long_record.abbre_img
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getAbbreImg() {
		return abbreImg;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.abbre_img
	 *
	 * @param abbreImg the value for user_long_record.abbre_img
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setAbbreImg(String abbreImg) {
		this.abbreImg = abbreImg;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.user_id
	 *
	 * @return the value of user_long_record.user_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.user_id
	 *
	 * @param userId the value for user_long_record.user_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.pet_id
	 *
	 * @return the value of user_long_record.pet_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getPetId() {
		return petId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.pet_id
	 *
	 * @param petId the value for user_long_record.pet_id
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setPetId(String petId) {
		this.petId = petId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.create_time
	 *
	 * @return the value of user_long_record.create_time
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.create_time
	 *
	 * @param createTime the value for user_long_record.create_time
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.check_state
	 *
	 * @return the value of user_long_record.check_state
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getCheckState() {
		return checkState;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.check_state
	 *
	 * @param checkState the value for user_long_record.check_state
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setCheckState(String checkState) {
		this.checkState = checkState;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.type
	 *
	 * @return the value of user_long_record.type
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.type
	 *
	 * @param type the value for user_long_record.type
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.check_by
	 *
	 * @return the value of user_long_record.check_by
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getCheckBy() {
		return checkBy;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.check_by
	 *
	 * @param checkBy the value for user_long_record.check_by
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setCheckBy(String checkBy) {
		this.checkBy = checkBy;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.check_datetime
	 *
	 * @return the value of user_long_record.check_datetime
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public Date getCheckDatetime() {
		return checkDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.check_datetime
	 *
	 * @param checkDatetime the value for user_long_record.check_datetime
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setCheckDatetime(Date checkDatetime) {
		this.checkDatetime = checkDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.del_flag
	 *
	 * @return the value of user_long_record.del_flag
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.del_flag
	 *
	 * @param delFlag the value for user_long_record.del_flag
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.memo
	 *
	 * @return the value of user_long_record.memo
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.memo
	 *
	 * @param memo the value for user_long_record.memo
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.recommend
	 *
	 * @return the value of user_long_record.recommend
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getRecommend() {
		return recommend;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.recommend
	 *
	 * @param recommend the value for user_long_record.recommend
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setRecommend(String recommend) {
		this.recommend = recommend;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column user_long_record.content
	 *
	 * @return the value of user_long_record.content
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column user_long_record.content
	 *
	 * @param content the value for user_long_record.content
	 *
	 * @mbggenerated Thu Nov 15 16:49:48 CST 2018
	 */
	public void setContent(String content) {
		this.content = content;
	}
}