package com.pokepet.model;

public class UserShoppingAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.id
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.user_id
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.receiver_name
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.receiver_phone
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    private String receiverPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.receiver_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    private String receiverAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.defult_flag
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    private String defultFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_shopping_address.del_flag
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.id
     *
     * @return the value of user_shopping_address.id
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.id
     *
     * @param id the value for user_shopping_address.id
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.user_id
     *
     * @return the value of user_shopping_address.user_id
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.user_id
     *
     * @param userId the value for user_shopping_address.user_id
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.receiver_name
     *
     * @return the value of user_shopping_address.receiver_name
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.receiver_name
     *
     * @param receiverName the value for user_shopping_address.receiver_name
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.receiver_phone
     *
     * @return the value of user_shopping_address.receiver_phone
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.receiver_phone
     *
     * @param receiverPhone the value for user_shopping_address.receiver_phone
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.receiver_address
     *
     * @return the value of user_shopping_address.receiver_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.receiver_address
     *
     * @param receiverAddress the value for user_shopping_address.receiver_address
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.defult_flag
     *
     * @return the value of user_shopping_address.defult_flag
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public String getDefultFlag() {
        return defultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.defult_flag
     *
     * @param defultFlag the value for user_shopping_address.defult_flag
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public void setDefultFlag(String defultFlag) {
        this.defultFlag = defultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_shopping_address.del_flag
     *
     * @return the value of user_shopping_address.del_flag
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_shopping_address.del_flag
     *
     * @param delFlag the value for user_shopping_address.del_flag
     *
     * @mbggenerated Thu May 24 14:44:58 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}