package com.pokepet.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nick_name
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile_phone
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.photo_path
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    private String photoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_datetime
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.chip_count
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    private Integer chipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.open_id
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    private String openId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nick_name
     *
     * @return the value of user.nick_name
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nick_name
     *
     * @param nickName the value for user.nick_name
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile_phone
     *
     * @return the value of user.mobile_phone
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile_phone
     *
     * @param mobilePhone the value for user.mobile_phone
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.photo_path
     *
     * @return the value of user.photo_path
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public String getPhotoPath() {
        return photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.photo_path
     *
     * @param photoPath the value for user.photo_path
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_datetime
     *
     * @return the value of user.create_datetime
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_datetime
     *
     * @param createDatetime the value for user.create_datetime
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.chip_count
     *
     * @return the value of user.chip_count
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public Integer getChipCount() {
        return chipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.chip_count
     *
     * @param chipCount the value for user.chip_count
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public void setChipCount(Integer chipCount) {
        this.chipCount = chipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.open_id
     *
     * @return the value of user.open_id
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.open_id
     *
     * @param openId the value for user.open_id
     *
     * @mbggenerated Wed Aug 08 18:21:31 GMT+08:00 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }
}