package com.pokepet.model;

import java.util.Date;

public class UserFollow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.user_id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.follow_user_id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    private String followUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.create_time
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_follow.del_flag
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.id
     *
     * @return the value of user_follow.id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.id
     *
     * @param id the value for user_follow.id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.user_id
     *
     * @return the value of user_follow.user_id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.user_id
     *
     * @param userId the value for user_follow.user_id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.follow_user_id
     *
     * @return the value of user_follow.follow_user_id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public String getFollowUserId() {
        return followUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.follow_user_id
     *
     * @param followUserId the value for user_follow.follow_user_id
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public void setFollowUserId(String followUserId) {
        this.followUserId = followUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.create_time
     *
     * @return the value of user_follow.create_time
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.create_time
     *
     * @param createTime the value for user_follow.create_time
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_follow.del_flag
     *
     * @return the value of user_follow.del_flag
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_follow.del_flag
     *
     * @param delFlag the value for user_follow.del_flag
     *
     * @mbggenerated Thu Aug 09 19:01:44 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}