package com.pokepet.model;

import java.util.Date;

public class UserWalkLocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_walk_location.id
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_walk_location.history_id
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    private String historyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_walk_location.longitude
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_walk_location.latitude
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_walk_location.create_datetime
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_walk_location.del_flag
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_walk_location.id
     *
     * @return the value of user_walk_location.id
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_walk_location.id
     *
     * @param id the value for user_walk_location.id
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_walk_location.history_id
     *
     * @return the value of user_walk_location.history_id
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public String getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_walk_location.history_id
     *
     * @param historyId the value for user_walk_location.history_id
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public void setHistoryId(String historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_walk_location.longitude
     *
     * @return the value of user_walk_location.longitude
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_walk_location.longitude
     *
     * @param longitude the value for user_walk_location.longitude
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_walk_location.latitude
     *
     * @return the value of user_walk_location.latitude
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_walk_location.latitude
     *
     * @param latitude the value for user_walk_location.latitude
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_walk_location.create_datetime
     *
     * @return the value of user_walk_location.create_datetime
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_walk_location.create_datetime
     *
     * @param createDatetime the value for user_walk_location.create_datetime
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_walk_location.del_flag
     *
     * @return the value of user_walk_location.del_flag
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_walk_location.del_flag
     *
     * @param delFlag the value for user_walk_location.del_flag
     *
     * @mbggenerated Mon May 28 17:12:56 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}