package com.pokepet.model;

public class UserPet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pet.id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pet.user_id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pet.pet_id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    private String petId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pet.del_flag
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pet.id
     *
     * @return the value of user_pet.id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pet.id
     *
     * @param id the value for user_pet.id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pet.user_id
     *
     * @return the value of user_pet.user_id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pet.user_id
     *
     * @param userId the value for user_pet.user_id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pet.pet_id
     *
     * @return the value of user_pet.pet_id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public String getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pet.pet_id
     *
     * @param petId the value for user_pet.pet_id
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public void setPetId(String petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pet.del_flag
     *
     * @return the value of user_pet.del_flag
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pet.del_flag
     *
     * @param delFlag the value for user_pet.del_flag
     *
     * @mbggenerated Thu May 24 13:39:27 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
}